# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[git_branch]
symbol = " "

################################################################################
# Disabled
################################################################################

[aws]
disabled = true

[buf]
disabled = true

[c]
disabled = true

[conda]
disabled = true

[docker_context]
disabled = true

[fossil_branch]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[hostname]
disabled = true

[meson]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[pijul_channel]
disabled = true

[python]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[spack]
disabled = true

[hg_branch]
disabled = true

[dart]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[nim]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[swift]
disabled = true

[zig]
disabled = true

[memory_usage]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[crystal]
disabled = true

[lua]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true
